name: CI

on:
  push:
    branches:
      - master
    pull_request:

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Install windows-build-tools
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm config set msvs_version 2019
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
